language: python

matrix:
  include:
    - python: 2.7
      os: linux
      before_install:
        - sudo apt-get install tcsh -y
        - sudo apt-get install csh -y
    # Travis CI does not support Python on Mac OS out of the box, this is a
    # simple workaround until they can. More info:
    # https://github.com/travis-ci/travis-ci/issues/2312
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install tcsh
        - rm /usr/local/bin/2to3-2
        - brew install python@2
        - export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
        - virtualenv env -p python2
        - source env/bin/activate
install:
  - 'python ./install.py ../rez_install'

script:
  - '"../rez_install/bin/rez/rez-selftest"'
